import gulp from 'gulp'

// Config
import paths from '../path.config'
import config from '../config'

// Clean packages
import clean from 'gulp-clean'
import fs from 'fs'

// Removing HTML generated by Nunjucks if in Craft mode
gulp.task('clean-html', (cb) => {
    if (config.project == 'craft') {
        fs.access('build/index.html', (err) => {
            if (!err) {
                return gulp.src(paths.clean, {read: false})
                    .pipe(clean())
                    .pipe(cb())
            } else {
                cb()
            }
        })
    } else {
        cb()
    }
})